#!/bin/ksh


while [ 1 ]; do


../client 204.131.41.107 8844 '
gameRequest_o:
gameRequest_o.id=1
gameRequest_o.state=8884
gameRequest_o.gameServer=
gameRequest_o.game=BINGO
gameRequest_o.gameid=1

'


sleep 20


../client 204.131.41.107 8844 '
gameRequest_o:
gameRequest_o.id=1
gameRequest_o.state=8885
gameRequest_o.gameServer=
gameRequest_o.game=BINGO
gameRequest_o.gameid=1

'

sleep 14

../bingocaller 204.131.41.107 8844


../client 204.131.41.107 8844 '
gameRequest_o:
gameRequest_o.id=1
gameRequest_o.state=8886
gameRequest_o.gameServer=
gameRequest_o.game=BINGO
gameRequest_o.gameid=1

';

sleep 14

done;





